### ISSUE TITLE
The documentation tab must not exist in the France connect plugin manager

### ISSUE THREAD

**Issue by mngham** [jalios/plugin-france-connect#1]
![documenationtab 1](https://user-images.githubusercontent.com/38217091/38501423-467b7b30-3c0d-11e8-986b-93eb11a2202c.jpg)
## Steps to Reproduce the Problem

1. As an administrator go to the plugin manager 
2. Click on France Connect Plugin 
## Actual Behavior
Seen :The documentation tab appears as you can see on the attached screenshot

**Comment by OlivierJaquemet** [comment]
Resolved, see : 8920205866ed3bb0915ef39164e716d0bfc86f2c

**Comment by mngham** [comment]
Validated in FranceConnect Plugin 1.9 (#40)
