### ISSUE TITLE
The France connect Kit menu is not closed after clicking outside the menu 

### ISSUE THREAD

**Issue by mngham** [jalios/plugin-france-connect#10]
## Steps to Reproduce the Problem

  1. Go to the Plugin manager /France Connect 
  2. Enable FranceConnect kit
  3. Connect as a France connect user
  4. Click on the France Connect kit Icon
Expected : The menu is opened but is incorrectly displayed (Please see the attached screenshot)
  5. Click outside the menu  

## Expected Behavior
The France connect Kit menu is closed >KO

## Actual Behavior
1. The France connect Kit menu is not closed automatically after clicking outside the menu

## Environment
![kitfranceconnect](https://user-images.githubusercontent.com/38217091/49737166-6aaace80-fc8c-11e8-86b3-25fe212e30db.png)

  - Navigator: All Navigators

**Comment by OlivierJaquemet** [comment]
FranceConnect Kit menu is a feature entirely provided by FranceConnect through integration of an external JavaScript code, its behavior cannot be changed --> Close as won't fix
