### ISSUE TITLE
The Plugin description is not fully translated into English

### ISSUE THREAD

**Issue by mngham** [jalios/plugin-france-connect#11]
## Steps to Reproduce the Problem

1. As an Admin go to the Plugin Manager
2. Click on the France connect plugin
Expected : The description in french is displayed  "Module d'authentification déléguée vers FranceConnect Particuliers, Entreprises ou Agents (https://franceconnect.gouv.fr)" >>OK
3. Change the site language to "English"
## Actual Behavior
The description in English is displayed but not fully translated  "FranceConnect Authentication plugin (https://franceconnect.gouv.fr)"

**Comment by OlivierJaquemet** [comment]
Won't fix : there are no translations for FC Particulier/Agent/Entreprise, that's why the english description is using less information.
