### ISSUE TITLE
The FranceConnect Kit does not appear in TopBar in JPlatform 10

### ISSUE THREAD

**Issue by mngham** [jalios/plugin-france-connect#2]
## Steps to Reproduce the Problem

1. As an administrator 
2. Go to the Plugin manager and click in France Connect Plugin 
3. Activate Kit FranceConnect property 
4. Connect as a FranceConnect user 

## Actual Behavior
The FranceConnect Kit does not appear in TopBar

**Comment by OlivierJaquemet** [comment]
Resolved, cf d3d9b57aa987af5c03ee55c352006be71eb9bb39

**Comment by mngham** [comment]
Validated in FranceConnect Plugin 1.9 (#40)
