### ISSUE TITLE
The Plugin description is not translated into English

### ISSUE THREAD

**Issue by mngham** [jalios/plugin-france-connect#3]
## Steps to Reproduce the Problem

  1. As an Admin go to the Plugin Manager
  2. Click on the France connect plugin
  3. Change the site language to "English"

## Actual Behavior

Seen: The Plugin description is not translated into English and the name of plugin must end with the "Plugin "word
![franceconnecttranslation 1](https://user-images.githubusercontent.com/38217091/38501676-d2f7eb52-3c0d-11e8-967c-027aa99b2c37.jpg)

**Comment by mngham** [comment]
![franceconnecttranslation 1](https://user-images.githubusercontent.com/38217091/38501610-bcb72eca-3c0d-11e8-9f8e-fcddbeeb7096.jpg)

**Comment by OlivierJaquemet** [comment]
Resolved, cf 9e9118e86a527ecd956cfb69acaf591272818deb

**Comment by mngham** [comment]
Validated in FranceConnect Plugin 1.9 (#40)
