### ISSUE TITLE
Make a generic OIDC plugin out of this one

### ISSUE THREAD

**Issue by mildis** [jalios/plugin-france-connect#8]
Not an issue per-se but as FranceConnect is based on OpenId Connect, would you make a generic OpenId Connect plugin ?  
Removing the type (agent, particulier, entreprise) logic and making URL configurable should do the trick.

**Comment by OlivierJaquemet** [comment]
@mildis thank you for this feedback.

We do have an RFE in the [SocialAuthenticationPlugin ](https://community.jalios.com/plugin/socialauth) to provide support for OpenId Connect : 
[SOCIALAUTH-12](https://issues.jalios.com/browse/SOCIALAUTH-12) (access to this link first requires a valid account on [Jalios Community website](https://community.jalios.com/)).
It is currently in the plugin's backlog, though I agree it would be nice to have.

That said, the FranceConnect plugin has some specific features that would not be provided by such improvement :

1. As required by the FranceConnect contract : 
   * modification of user firstname, lastname, email, and other information retrieved through FC are fobidden (see corresponding DataController in the source).
   * use of dedicated France Connect login icon (provided by FC, and packaged in the plugin)
2. preconfigured endpoints URL for simpler configuration (for JCMS/JPlatform administrators)


Fill free to reopen this issue if you want to provide more arguments on this matter.
I'm always open to discussion !

**Comment by mildis** [comment]
@OlivierJaquemet Thanks for your feedback.
I saw this RFE but as it's near 2yrs old, I was wondering if it was still alive.

The readonly nature of the FranceConnect plugin OK for OIDC : updating user values often requires to go back to the IDP and use its own forms. Thus having the user informations RO is OK.  
Surely, FranceConnect LnF is specific. OpenId has its own [set of icons](https://openid.net/add-openid/logos/)  

OpenId has a discovery procedure that requires only one URL to be provided, then you hit `/.well-known/openid-configuration` and retrieve a JSON with all wanted endpoints and supported algs and claims.

I don't know if you want an OpenId Connect plugin to act as an SP only or if you want to go full-monty and make Jalios an IDP for external clients too.

**Comment by OlivierJaquemet** [comment]
As you probably already know, we have many opened RFE. All of them are being considered when we can find the time to work on the corresponding projects. Those we really don't want to do gets closed. So yes, [SOCIALAUTH-12](https://issues.jalios.com/browse/SOCIALAUTH-12) is still alive.

Transforming Jalios JPlatform in an IdP supporting OAuth/OIDC is also really being considered for 2019 as it would greatly simplify developpement with other frameworks / solutions.

That said, I do not have any schedule for those possible improvements.

**Comment by mildis** [comment]
Glad to hear.
Will try to make SAML work ...

**Comment by OlivierJaquemet** [comment]
As an IDP ?

**Comment by mildis** [comment]
Oh god no :-D just as a SP.

**Comment by OlivierJaquemet** [comment]
For that purpose we already have a working plugin : https://community.jalios.com/plugin/saml
