### ISSUE TITLE
No message displayed when we try to disconnect from France connect particular

### ISSUE THREAD

**Issue by mngham** [jalios/plugin-france-connect#9]
## Steps to Reproduce the Problem

  1. Try to connect to the France Connect particular/Agents
  2. Disconnect from JPlatform 
  
## Expected Behavior
The message "Please close the browser to ensure a perfect disconnection" is displayed >>KO 

## Actual Behavior

The message "Please close the browser to ensure a perfect disconnection" is  not displayed  and  we are definitively disconnected

**Comment by OlivierJaquemet** [comment]
This behavior was voluntarly modified by France Connect, as explained in this following mail received from FC support on 19/12/2018 à 16:52 : 

> Bonjour,
> 
> Nous vous remercions pour ce retour. L'écran de déconnexion vient tout juste d'être supprimé des cinématiques suite à des retours consommateurs négatifs.
> Notre documentation n'est en effet pas encore à jour, nous nous excusons pour ce point et nous le corrigerons au plus vite.
> 
> Merci pour votre compréhension.
>
> Cordialement,
> 
> AL pour l’équipe support FranceConnect


--> Close as won't fix.
